package finance.insurance;

import java.util.UUID;

public final class InsuranceClaim {
    private final UUID id,policyId,eventId,applicantId;private final long reportedAmount,verifiedLoss,approvedAmount,createdDay,reviewedDay,approvedDay;private ClaimStatus status;private String reason,evidence;private long paidAmount,lastPaymentDay;private UUID paymentTransactionId;
    public InsuranceClaim(UUID id,UUID policyId,UUID eventId,UUID applicantId,long reportedAmount,long verifiedLoss,long approvedAmount,long createdDay,long reviewedDay,long approvedDay,ClaimStatus status,String reason,String evidence,long paidAmount,long lastPaymentDay,UUID paymentTransactionId){if(id==null||policyId==null||eventId==null||applicantId==null||reportedAmount<0||verifiedLoss<0||approvedAmount<0||paidAmount<0||paidAmount>approvedAmount||createdDay<0||status==null)throw new IllegalArgumentException();this.id=id;this.policyId=policyId;this.eventId=eventId;this.applicantId=applicantId;this.reportedAmount=reportedAmount;this.verifiedLoss=verifiedLoss;this.approvedAmount=approvedAmount;this.createdDay=createdDay;this.reviewedDay=reviewedDay;this.approvedDay=approvedDay;this.status=status;this.reason=reason==null?"":reason;this.evidence=evidence==null?"":evidence;this.paidAmount=paidAmount;this.lastPaymentDay=lastPaymentDay;this.paymentTransactionId=paymentTransactionId;}
    public UUID id(){return id;}public UUID policyId(){return policyId;}public UUID eventId(){return eventId;}public UUID applicantId(){return applicantId;}public long reportedAmount(){return reportedAmount;}public long verifiedLoss(){return verifiedLoss;}public long approvedAmount(){return approvedAmount;}public long createdDay(){return createdDay;}public long reviewedDay(){return reviewedDay;}public long approvedDay(){return approvedDay;}public ClaimStatus status(){return status;}public String reason(){return reason;}public String evidence(){return evidence;}public long paidAmount(){return paidAmount;}public long unpaidAmount(){return approvedAmount-paidAmount;}public long lastPaymentDay(){return lastPaymentDay;}public UUID paymentTransactionId(){return paymentTransactionId;}
    void paid(long amount,long day,UUID tx){if(amount<=0||amount>unpaidAmount())throw new IllegalArgumentException();paidAmount+=amount;lastPaymentDay=day;paymentTransactionId=tx;status=paidAmount==approvedAmount?ClaimStatus.PAID:ClaimStatus.PARTIALLY_PAID;}public void restoreStatus(ClaimStatus value,String reason){status=value;this.reason=reason==null?"":reason;}
}
