package finance.insurance;

import java.util.UUID;

public final class InsurancePolicy {
    private final UUID id,holderId,companyId,insuredObjectId,beneficiaryId,premiumTransactionId;
    private final InsuranceProduct product; private final long effectiveDay,expiryDay,coverageLimit,deductible,premium;
    private final int payoutRatioBps,riskFactorBps,version; private PolicyStatus status; private long remainingLimit,lastUpdatedDay;
    public InsurancePolicy(UUID id,InsuranceProduct product,UUID holderId,UUID companyId,UUID insuredObjectId,UUID beneficiaryId,long effectiveDay,long expiryDay,PolicyStatus status,long coverageLimit,long deductible,int payoutRatioBps,long remainingLimit,long premium,UUID premiumTransactionId,int riskFactorBps,int version,long lastUpdatedDay){if(id==null||product==null||holderId==null||insuredObjectId==null||beneficiaryId==null||premiumTransactionId==null||effectiveDay<0||expiryDay<=effectiveDay||coverageLimit<=0||deductible<0||payoutRatioBps<=0||payoutRatioBps>10_000||remainingLimit<0||remainingLimit>coverageLimit||premium<=0||riskFactorBps<=0||version<=0)throw new IllegalArgumentException();this.id=id;this.product=product;this.holderId=holderId;this.companyId=companyId;this.insuredObjectId=insuredObjectId;this.beneficiaryId=beneficiaryId;this.effectiveDay=effectiveDay;this.expiryDay=expiryDay;this.status=status;this.coverageLimit=coverageLimit;this.deductible=deductible;this.payoutRatioBps=payoutRatioBps;this.remainingLimit=remainingLimit;this.premium=premium;this.premiumTransactionId=premiumTransactionId;this.riskFactorBps=riskFactorBps;this.version=version;this.lastUpdatedDay=lastUpdatedDay;}
    public UUID id(){return id;}public InsuranceProduct product(){return product;}public UUID holderId(){return holderId;}public UUID companyId(){return companyId;}public UUID insuredObjectId(){return insuredObjectId;}public UUID beneficiaryId(){return beneficiaryId;}public long effectiveDay(){return effectiveDay;}public long expiryDay(){return expiryDay;}public PolicyStatus status(){return status;}public long coverageLimit(){return coverageLimit;}public long deductible(){return deductible;}public int payoutRatioBps(){return payoutRatioBps;}public long remainingLimit(){return remainingLimit;}public long premium(){return premium;}public UUID premiumTransactionId(){return premiumTransactionId;}public int riskFactorBps(){return riskFactorBps;}public int version(){return version;}public long lastUpdatedDay(){return lastUpdatedDay;}
    boolean activeAt(long day){return status==PolicyStatus.ACTIVE&&day>=effectiveDay&&day<=expiryDay&&remainingLimit>0;}void expire(long day){status=PolicyStatus.EXPIRED;lastUpdatedDay=day;}void consume(long amount,long day){if(amount<=0||amount>remainingLimit)throw new IllegalArgumentException();remainingLimit-=amount;lastUpdatedDay=day;if(remainingLimit==0)status=PolicyStatus.EXHAUSTED;}public void restoreStatus(PolicyStatus s,long day){status=s;lastUpdatedDay=day;}
}
