package finance.exploration;
import finance.account.AccountManager;import finance.data.EconomySavedData;import finance.data.serializer.ExplorationDataSerializer;import finance.diagnostic.ModuleHealthRegistry;import net.minecraft.core.BlockPos;import net.minecraft.nbt.CompoundTag;import org.junit.jupiter.api.*;import java.util.UUID;import static org.junit.jupiter.api.Assertions.*;
class ExplorationManagerTest {
 @BeforeEach void setup(){EconomySavedData.resetRuntimeState();ModuleHealthRegistry.clear();}@AfterEach void cleanup(){EconomySavedData.resetRuntimeState();}
 @Test void onePlayerCannotOwnTwoActiveAssignments(){UUID player=UUID.randomUUID();assertTrue(ExplorationManager.add(assignment(player,ExplorationStatus.ACTIVE,100)));assertFalse(ExplorationManager.add(assignment(player,ExplorationStatus.ACTIVE,100)));assertEquals(1,ExplorationManager.assignments().size());}
 @Test void assignmentCooldownAndEscrowRoundTrip(){UUID player=UUID.randomUUID();ExplorationAssignment a=assignment(player,ExplorationStatus.ACTIVE,250);AccountManager.getOrCreateSystemAccount(a.escrowId()).deposit(250);assertTrue(ExplorationManager.add(a));ExplorationManager.recordRequest(player,7);CompoundTag root=new CompoundTag();ExplorationDataSerializer.save(root);ExplorationManager.clearDirect();ExplorationDataSerializer.load(root);assertEquals(a.target(),ExplorationManager.get(a.id()).target());assertEquals(7,ExplorationManager.lastRequestDay(player));assertTrue(ModuleHealthRegistry.mayWrite(ModuleHealthRegistry.Module.EXPLORATION));}
 @Test void corruptEscrowPausesOnlyExplorationAndPreservesMoney(){UUID player=UUID.randomUUID();ExplorationAssignment a=assignment(player,ExplorationStatus.ACTIVE,250);AccountManager.getOrCreateSystemAccount(a.escrowId()).deposit(200);ExplorationManager.add(a);CompoundTag root=new CompoundTag();ExplorationDataSerializer.save(root);ExplorationManager.clearDirect();ExplorationDataSerializer.load(root);assertEquals(ExplorationStatus.QUARANTINED,ExplorationManager.get(a.id()).status());assertFalse(ModuleHealthRegistry.mayWrite(ModuleHealthRegistry.Module.EXPLORATION));assertEquals(200,AccountManager.getAccounts().get(a.escrowId()).getBalance());assertTrue(ModuleHealthRegistry.mayWrite(ModuleHealthRegistry.Module.CONTRACT));}
 @Test void terminalHistoryIsBoundedWithoutRemovingLiveAssignment(){UUID player=UUID.randomUUID();assertTrue(ExplorationManager.add(assignment(player,ExplorationStatus.ACTIVE,10)));for(int i=0;i<300;i++)assertTrue(ExplorationManager.restore(assignment(UUID.randomUUID(),ExplorationStatus.CANCELLED,10)));ExplorationManager.prune();assertNotNull(ExplorationManager.activeFor(player));assertEquals(ExplorationManager.MAX_TERMINAL_HISTORY+1,ExplorationManager.assignments().size());}
 @Test void pruningTerminalHistoryAlsoRemovesEmptyEscrowAccounts(){for(int i=0;i<300;i++){ExplorationAssignment a=assignment(UUID.randomUUID(),ExplorationStatus.CANCELLED,10);AccountManager.getOrCreateSystemAccount(a.escrowId());assertTrue(ExplorationManager.restore(a));}ExplorationManager.prune();assertEquals(ExplorationManager.MAX_TERMINAL_HISTORY,ExplorationManager.assignments().size());assertEquals(ExplorationManager.MAX_TERMINAL_HISTORY,AccountManager.getAccounts().size());}
 private ExplorationAssignment assignment(UUID player,ExplorationStatus status,long reward){return new ExplorationAssignment(UUID.randomUUID(),player,UUID.randomUUID(),"minecraft:overworld",new BlockPos(100,64,100),ExplorationTargetType.SETTLEMENT,"plains_trade",reward,1,8,status);}
}
