package finance.network;

import finance.bank.*;import finance.debt.*;import net.minecraft.network.FriendlyByteBuf;import net.minecraftforge.api.distmarker.Dist;import net.minecraftforge.fml.DistExecutor;import net.minecraftforge.network.NetworkEvent;import java.util.*;import java.util.function.Supplier;
public record BankResponsePacket(long requestId,boolean admin,long insuranceFund,int overnightRateBps,List<BankRow>banks,List<AccountRow>accounts,List<TimeRow>timeDeposits,List<LoanRow>loans){public static final int MAX_ROWS=64;
 public record BankRow(UUID id,String code,String name,BankStatus status,long assets,long reserves,long requiredReserves,long deposits,long equity,int capitalBps,int liquidityBps,int demandRateBps,int timeRateBps,long centralBorrowing){}
 public record AccountRow(UUID id,UUID bankId,CustomerType ownerType,BankAccountType type,long balance,long frozen){}
 public record TimeRow(UUID id,UUID bankId,long principal,int rateBps,long maturityDay,long accruedInterest,TimeDepositStatus status){}
 public record LoanRow(UUID id,UUID companyId,LoanLenderType lenderType,UUID lenderId,long outstanding,long interest,int rateBps,long maturityDay,LoanStatus status){}
 public BankResponsePacket{if(requestId<=0)throw new IllegalArgumentException();banks=bounded(banks);accounts=bounded(accounts);timeDeposits=bounded(timeDeposits);loans=bounded(loans);}private static<T>List<T>bounded(List<T>x){return x==null?List.of():List.copyOf(x.subList(0,Math.min(MAX_ROWS,x.size())));}
 public static void encode(BankResponsePacket p,FriendlyByteBuf b){b.writeLong(p.requestId);b.writeBoolean(p.admin);b.writeLong(p.insuranceFund);b.writeInt(p.overnightRateBps);writeCount(b,p.banks.size());for(var r:p.banks){b.writeUUID(r.id);b.writeUtf(r.code,16);b.writeUtf(r.name,64);b.writeEnum(r.status);b.writeLong(r.assets);b.writeLong(r.reserves);b.writeLong(r.requiredReserves);b.writeLong(r.deposits);b.writeLong(r.equity);b.writeInt(r.capitalBps);b.writeInt(r.liquidityBps);b.writeInt(r.demandRateBps);b.writeInt(r.timeRateBps);b.writeLong(r.centralBorrowing);}writeCount(b,p.accounts.size());for(var r:p.accounts){b.writeUUID(r.id);b.writeUUID(r.bankId);b.writeEnum(r.ownerType);b.writeEnum(r.type);b.writeLong(r.balance);b.writeLong(r.frozen);}writeCount(b,p.timeDeposits.size());for(var r:p.timeDeposits){b.writeUUID(r.id);b.writeUUID(r.bankId);b.writeLong(r.principal);b.writeInt(r.rateBps);b.writeLong(r.maturityDay);b.writeLong(r.accruedInterest);b.writeEnum(r.status);}writeCount(b,p.loans.size());for(var r:p.loans){b.writeUUID(r.id);b.writeUUID(r.companyId);b.writeEnum(r.lenderType);b.writeUUID(r.lenderId);b.writeLong(r.outstanding);b.writeLong(r.interest);b.writeInt(r.rateBps);b.writeLong(r.maturityDay);b.writeEnum(r.status);}}
 public static BankResponsePacket decode(FriendlyByteBuf b){long request=b.readLong();boolean admin=b.readBoolean();long fund=b.readLong();int rate=b.readInt();int n=count(b);List<BankRow>banks=new ArrayList<>(n);for(int i=0;i<n;i++)banks.add(new BankRow(b.readUUID(),b.readUtf(16),b.readUtf(64),b.readEnum(BankStatus.class),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readInt(),b.readInt(),b.readInt(),b.readInt(),b.readLong()));n=count(b);List<AccountRow>accounts=new ArrayList<>(n);for(int i=0;i<n;i++)accounts.add(new AccountRow(b.readUUID(),b.readUUID(),b.readEnum(CustomerType.class),b.readEnum(BankAccountType.class),b.readLong(),b.readLong()));n=count(b);List<TimeRow>terms=new ArrayList<>(n);for(int i=0;i<n;i++)terms.add(new TimeRow(b.readUUID(),b.readUUID(),b.readLong(),b.readInt(),b.readLong(),b.readLong(),b.readEnum(TimeDepositStatus.class)));n=count(b);List<LoanRow>loans=new ArrayList<>(n);for(int i=0;i<n;i++)loans.add(new LoanRow(b.readUUID(),b.readUUID(),b.readEnum(LoanLenderType.class),b.readUUID(),b.readLong(),b.readLong(),b.readInt(),b.readLong(),b.readEnum(LoanStatus.class)));return new BankResponsePacket(request,admin,fund,rate,banks,accounts,terms,loans);}
 private static void writeCount(FriendlyByteBuf b,int n){b.writeVarInt(n);}private static int count(FriendlyByteBuf b){int n=b.readVarInt();if(n<0||n>MAX_ROWS)throw new IllegalArgumentException("bank row limit");return n;}public static void handle(BankResponsePacket p,Supplier<NetworkEvent.Context>s){var c=s.get();c.enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->finance.client.BankClientCache.accept(p)));c.setPacketHandled(true);}}
