package finance.network;

import finance.futures.*;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.fml.DistExecutor;
import net.minecraftforge.network.NetworkEvent;
import java.util.*;
import java.util.function.Supplier;

public record FuturesResponsePacket(long requestId,long marginCash,long frozen,long equity,long initialRequired,long maintenanceRequired,long withdrawable,MarginRiskStatus riskStatus,long guaranteeFund,long todayFundUse,List<ContractRow> contracts,List<PositionRow> positions,List<OrderRow> orders,List<SettlementRow> settlements){
    public static final int MAX_ROWS=64;public record ContractRow(UUID id,String code,String commodity,FuturesContractStatus status,long size,long lastTradingDay,long maturityDay,long lastPrice,long settlementPrice,long spotPrice,long openInterest,long dailyVolume){}
    public record PositionRow(UUID contractId,long signedQuantity,long averagePrice,long settlementReference,long unrealized,long realized){}
    public record OrderRow(UUID orderId,UUID contractId,FuturesOrderSide side,long price,long quantity,boolean owned){}
    public record SettlementRow(UUID contractId,long day,long price,long fundUse,long haircut,boolean finalSettlement){}
    public FuturesResponsePacket{if(requestId<=0||riskStatus==null)throw new IllegalArgumentException();contracts=bounded(contracts);positions=bounded(positions);orders=bounded(orders);settlements=bounded(settlements);}
    private static<T>List<T>bounded(List<T>x){return x==null?List.of():List.copyOf(x.subList(0,Math.min(MAX_ROWS,x.size())));}
    public static void encode(FuturesResponsePacket p,FriendlyByteBuf b){b.writeLong(p.requestId);b.writeLong(p.marginCash);b.writeLong(p.frozen);b.writeLong(p.equity);b.writeLong(p.initialRequired);b.writeLong(p.maintenanceRequired);b.writeLong(p.withdrawable);b.writeEnum(p.riskStatus);b.writeLong(p.guaranteeFund);b.writeLong(p.todayFundUse);b.writeVarInt(p.contracts.size());for(var r:p.contracts){b.writeUUID(r.id);b.writeUtf(r.code,16);b.writeUtf(r.commodity,64);b.writeEnum(r.status);b.writeLong(r.size);b.writeLong(r.lastTradingDay);b.writeLong(r.maturityDay);b.writeLong(r.lastPrice);b.writeLong(r.settlementPrice);b.writeLong(r.spotPrice);b.writeLong(r.openInterest);b.writeLong(r.dailyVolume);}b.writeVarInt(p.positions.size());for(var r:p.positions){b.writeUUID(r.contractId);b.writeLong(r.signedQuantity);b.writeLong(r.averagePrice);b.writeLong(r.settlementReference);b.writeLong(r.unrealized);b.writeLong(r.realized);}b.writeVarInt(p.orders.size());for(var r:p.orders){b.writeUUID(r.orderId);b.writeUUID(r.contractId);b.writeEnum(r.side);b.writeLong(r.price);b.writeLong(r.quantity);b.writeBoolean(r.owned);}b.writeVarInt(p.settlements.size());for(var r:p.settlements){b.writeUUID(r.contractId);b.writeLong(r.day);b.writeLong(r.price);b.writeLong(r.fundUse);b.writeLong(r.haircut);b.writeBoolean(r.finalSettlement);}}
    public static FuturesResponsePacket decode(FriendlyByteBuf b){long id=b.readLong(),cash=b.readLong(),frozen=b.readLong(),equity=b.readLong(),initial=b.readLong(),maintenance=b.readLong(),withdrawable=b.readLong();var risk=b.readEnum(MarginRiskStatus.class);long fund=b.readLong(),use=b.readLong();int cc=count(b);List<ContractRow>cs=new ArrayList<>(cc);for(int i=0;i<cc;i++)cs.add(new ContractRow(b.readUUID(),b.readUtf(16),b.readUtf(64),b.readEnum(FuturesContractStatus.class),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readLong()));int pc=count(b);List<PositionRow>ps=new ArrayList<>(pc);for(int i=0;i<pc;i++)ps.add(new PositionRow(b.readUUID(),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readLong()));int oc=count(b);List<OrderRow>os=new ArrayList<>(oc);for(int i=0;i<oc;i++)os.add(new OrderRow(b.readUUID(),b.readUUID(),b.readEnum(FuturesOrderSide.class),b.readLong(),b.readLong(),b.readBoolean()));int sc=count(b);List<SettlementRow>ss=new ArrayList<>(sc);for(int i=0;i<sc;i++)ss.add(new SettlementRow(b.readUUID(),b.readLong(),b.readLong(),b.readLong(),b.readLong(),b.readBoolean()));return new FuturesResponsePacket(id,cash,frozen,equity,initial,maintenance,withdrawable,risk,fund,use,cs,ps,os,ss);}
    private static int count(FriendlyByteBuf b){int n=b.readVarInt();if(n<0||n>MAX_ROWS)throw new IllegalArgumentException("futures row limit");return n;}
    public static void handle(FuturesResponsePacket p,Supplier<NetworkEvent.Context>s){var c=s.get();c.enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->finance.client.FuturesClientCache.accept(p)));c.setPacketHandled(true);}
}
