package finance.network;

import finance.company.CompanyManager;
import finance.insurance.*;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraftforge.network.*;
import java.util.function.Supplier;

public record InsuranceRequestPacket(long requestId){public static void encode(InsuranceRequestPacket p,FriendlyByteBuf b){b.writeLong(p.requestId);}public static InsuranceRequestPacket decode(FriendlyByteBuf b){return new InsuranceRequestPacket(b.readLong());}public static void handle(InsuranceRequestPacket p,Supplier<NetworkEvent.Context>s){var c=s.get();c.enqueueWork(()->{var player=c.getSender();if(player==null||p.requestId<=0||!MarketDataRequestLimiter.allow(player.getUUID(),player.server.getTickCount(),"insurance-data"))return;var company=CompanyManager.getCompanyByOwner(player.getUUID());var policies=InsuranceManager.policies().values().stream().filter(x->x.holderId().equals(player.getUUID())||player.hasPermissions(2)).limit(128).map(x->new InsuranceResponsePacket.PolicyRow(x.id(),x.product(),x.companyId(),x.insuredObjectId(),x.status(),x.effectiveDay(),x.expiryDay(),x.coverageLimit(),x.remainingLimit(),x.premium())).toList();var claims=InsuranceManager.claims().values().stream().filter(x->{var policy=InsuranceManager.policies().get(x.policyId());return policy!=null&&(policy.holderId().equals(player.getUUID())||player.hasPermissions(2));}).limit(128).map(x->new InsuranceResponsePacket.ClaimRow(x.id(),x.policyId(),x.eventId(),x.status(),x.verifiedLoss(),x.approvedAmount(),x.paidAmount(),x.reason())).toList();CompanyRiskService.Summary risk=company==null?CompanyRiskService.calculate(null):CompanyRiskService.calculate(company);FinancePacketHandler.CHANNEL.send(PacketDistributor.PLAYER.with(()->player),new InsuranceResponsePacket(p.requestId,player.hasPermissions(2),finance.account.AccountManager.getBalance(InsurancePool.ACCOUNT_ID),InsuranceManager.activeExposure(),InsuranceManager.approvedUnpaid(),policies,claims,risk));});c.setPacketHandled(true);}}
