package finance.feedback;

public enum WorldFeedbackType {
    MARKET_SHORTAGE, MARKET_RECOVERY, LARGE_CONTRACT, COMPANY_RISK, COMPANY_RECOVERY,
    BANK_RESTRICTED, BANK_RESOLUTION, INSURANCE_EVENT, MAJOR_MARKET_EVENT
}
