package finance.governance;
import finance.account.AccountManager;import finance.company.*;import finance.data.EconomySavedData;import finance.stock.*;import net.minecraft.nbt.CompoundTag;import net.minecraft.nbt.ListTag;import org.junit.jupiter.api.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class CorporateActionManagerTest{UUID owner=UUID.fromString("00000000-0000-0000-0000-000000010001"),buyer=UUID.fromString("00000000-0000-0000-0000-000000010002"),seller=UUID.fromString("00000000-0000-0000-0000-000000010003"),companyId=UUID.fromString("00000000-0000-0000-0000-000000010004");Company company;Stock stock;@BeforeEach void setup(){EconomySavedData.resetRuntimeState();company=new Company(companyId,"Governed",CompanyType.RAW_MATERIALS,100_000,owner);company.setPublic(true);CompanyManager.registerDirect(company);stock=new Stock("GOVR","Governed",companyId,100,100,0,100,100);StockMarketManager.putStockDirect(stock);StockPortfolioManager.addHolding(buyer,"GOVR",20,100);StockPortfolioManager.addHolding(seller,"GOVR",80,100);AccountManager.deposit(buyer,100_000);}@AfterEach void clean(){EconomySavedData.resetRuntimeState();}
 @Test void recordDateSnapshotDoesNotChangeAfterTrading(){var made=CompanyProposalManager.createProposal(owner,companyId,CompanyProposalType.RENAME,"New",0,0,0,0,2,.5);assertTrue(made.success());var p=CompanyProposalManager.getProposals().get(0);assertEquals(20,p.getSnapshotPower(buyer));StockPortfolioManager.removeHolding(seller,"GOVR",10);StockPortfolioManager.addHolding(buyer,"GOVR",10,100);assertTrue(CompanyProposalManager.vote(buyer,p.getProposalId(),true,1).success());assertEquals(20,p.getYesVotes());}
 @Test void buybackUsesCompanyCashAndCreatesNonVotingTreasuryShares(){long companyBefore=company.getCash(),sellerBefore=AccountManager.getBalance(seller);var opened=openBuyback(100,20,1,0);assertTrue(opened.success(),opened.message());assertEquals(companyBefore-2_000,company.getCash());assertTrue(CorporateActionManager.acceptBuyback(seller,opened.id(),20,0,"ba1").success());assertEquals(60,StockPortfolioManager.getHolding(seller,"GOVR").getQuantity());CorporateActionManager.processDay(1);assertEquals(20,stock.getTreasuryShares());assertEquals(80,stock.getVotingShares());assertEquals(sellerBefore+2_000,AccountManager.getBalance(seller));assertFalse(CorporateActionManager.startBuyback(owner,companyId,100,20,1,1,"proposal-"+CompanyProposalManager.getProposals().get(0).getProposalId()).success());}
 @Test void oversubscribedTenderAllocatesExactlyAndTransfersControl(){var opened=CorporateActionManager.startTender(buyer,companyId,100,40,30,1,0,"t1");assertTrue(opened.success(),opened.message());assertTrue(CorporateActionManager.acceptTender(seller,opened.id(),60,0,"ta1").success());CorporateActionManager.processDay(1);assertEquals(60,StockPortfolioManager.getHolding(buyer,"GOVR").getQuantity());assertEquals(40,StockPortfolioManager.getHolding(seller,"GOVR").getQuantity());assertEquals(buyer,CorporateActionManager.controllers().get(companyId));assertEquals(0,AccountManager.getBalance(CorporateActionManager.tenders().get(opened.id()).escrowId()));}
 @Test void failedTenderRestoresFundsAndSharesAcrossPersistence(){long cash=AccountManager.getBalance(buyer);var opened=CorporateActionManager.startTender(buyer,companyId,100,40,30,2,0,"t2");assertTrue(CorporateActionManager.acceptTender(seller,opened.id(),10,0,"ta2").success());CompoundTag saved=new EconomySavedData().save(new CompoundTag());EconomySavedData.resetRuntimeState();EconomySavedData.load(saved);CorporateActionManager.processDay(2);assertEquals(cash,AccountManager.getBalance(buyer));assertEquals(80,StockPortfolioManager.getHolding(seller,"GOVR").getQuantity());assertEquals(CapitalActionStatus.FAILED,CorporateActionManager.tenders().get(opened.id()).status());}
 @Test void cancellingBuybackRestoresCompanyCashAndLockedShares(){long cash=company.getCash();var opened=openBuyback(100,20,5,0);assertTrue(CorporateActionManager.acceptBuyback(seller,opened.id(),15,0,"ba-cancel").success());assertTrue(CorporateActionManager.cancelBuyback(owner,opened.id(),1,"cancel-1").success());assertEquals(cash,company.getCash());assertEquals(80,StockPortfolioManager.getHolding(seller,"GOVR").getQuantity());assertEquals(CapitalActionStatus.CANCELLED,CorporateActionManager.buybacks().get(opened.id()).status());assertFalse(CorporateActionManager.cancelBuyback(owner,opened.id(),1,"cancel-1").success());}
 @Test void cancellationPreservesOriginalHoldingCost(){var opened=openBuyback(100,20,5,0);assertTrue(CorporateActionManager.acceptBuyback(seller,opened.id(),15,0,"ba-cost").success());assertTrue(CorporateActionManager.cancelBuyback(owner,opened.id(),1,"cancel-cost").success());assertEquals(100,StockPortfolioManager.getHolding(seller,"GOVR").getAverageCost());}
 @Test void persistencePreservesCostOfCorporateLockedShares(){var opened=CorporateActionManager.startTender(buyer,companyId,120,20,20,5,0,"t-cost");assertTrue(CorporateActionManager.acceptTender(seller,opened.id(),15,0,"ta-cost").success());CompoundTag saved=new EconomySavedData().save(new CompoundTag());EconomySavedData.resetRuntimeState();EconomySavedData.load(saved);assertTrue(CorporateActionManager.cancelTender(buyer,opened.id(),1,"tc-cost").success());assertEquals(100,StockPortfolioManager.getHolding(seller,"GOVR").getAverageCost());}
 @Test void corruptOpenTenderIsQuarantinedAndRestoresEscrowAndShares(){long cash=AccountManager.getBalance(buyer);var opened=CorporateActionManager.startTender(buyer,companyId,120,20,20,5,0,"t-corrupt");assertTrue(CorporateActionManager.acceptTender(seller,opened.id(),15,0,"ta-corrupt").success());CompoundTag saved=new EconomySavedData().save(new CompoundTag());ListTag tenders=saved.getCompound("Governance").getList("Tenders",10);tenders.getCompound(0).putLong("Minimum",Long.MAX_VALUE);EconomySavedData.resetRuntimeState();EconomySavedData.load(saved);assertTrue(CorporateActionManager.tenders().isEmpty());assertEquals(cash,AccountManager.getBalance(buyer));assertEquals(80,StockPortfolioManager.getHolding(seller,"GOVR").getQuantity());assertEquals(100,StockPortfolioManager.getHolding(seller,"GOVR").getAverageCost());}
 @Test void treasuryRetirementReducesTotalAndVotingSharesWithoutCreatingHoldings(){var opened=openBuyback(100,10,1,0);assertTrue(CorporateActionManager.acceptBuyback(seller,opened.id(),10,0,"ba-retire").success());CorporateActionManager.processDay(1);String key=authorization(CompanyProposalType.TREASURY_RETIREMENT,10,0,0);assertTrue(CorporateActionManager.retireTreasury(owner,companyId,10,2,key).success());assertEquals(90,stock.getTotalShares());assertEquals(90,stock.getVotingShares());assertEquals(0,stock.getTreasuryShares());assertEquals(90,StockPortfolioManager.getHoldingsForCompany("GOVR").values().stream().mapToLong(Long::longValue).sum());}
 @Test void directClientCannotBypassBuybackOrTreasuryVote(){long cash=company.getCash();assertFalse(CorporateActionManager.startBuyback(owner,companyId,100,10,2,0,"forged").success());assertEquals(cash,company.getCash());assertFalse(CorporateActionManager.retireTreasury(owner,companyId,1,0,"forged").success());}
 @Test void openActionCapacityRejectsNewEscrowWithoutLosingExistingActions(){for(int i=0;i<CorporateActionManager.MAX_ACTIONS;i++){UUID id=UUID.randomUUID();CorporateActionManager.putBuybackDirect(new BuybackPlan(id,companyId,UUID.randomUUID(),"GOVR",1,1,0,10,1,CapitalActionStatus.OPEN));}long cash=company.getCash();assertFalse(openBuyback(100,1,1,0).success());assertEquals(cash,company.getCash());assertEquals(CorporateActionManager.MAX_ACTIONS,CorporateActionManager.buybacks().size());}
 @Test void persistenceDoesNotTruncateActionsAfterLegacyLimit(){for(int i=0;i<CorporateActionManager.MAX_ACTIONS+1;i++){UUID id=UUID.randomUUID();CorporateActionManager.putBuybackDirect(new BuybackPlan(id,companyId,UUID.randomUUID(),"GOVR",1,1,0,1,1,CapitalActionStatus.COMPLETED));}CompoundTag saved=new EconomySavedData().save(new CompoundTag());EconomySavedData.resetRuntimeState();EconomySavedData.load(saved);assertEquals(CorporateActionManager.MAX_ACTIONS+1,CorporateActionManager.buybacks().size());}
 private CorporateActionManager.Result openBuyback(long price,long shares,int duration,long day){return CorporateActionManager.startBuyback(owner,companyId,price,shares,duration,day,authorization(CompanyProposalType.SHARE_BUYBACK,price,shares,duration));}
 private String authorization(CompanyProposalType type,long v1,long v2,long v3){CompanyProposal p=new CompanyProposal(companyId,owner,type,"approved","",v1,v2,v3,0,10,.5);p.finish(CompanyProposalStatus.PASSED,"approved");CompanyProposalManager.addProposalDirect(p);return "proposal-"+p.getProposalId();}
}
