package finance.bank;

import finance.account.AccountManager;import finance.data.EconomySavedData;import org.junit.jupiter.api.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class BankingManagerTest {UUID player=UUID.fromString("00000000-0000-0000-0000-000000006001"),other=UUID.fromString("00000000-0000-0000-0000-000000006002");CommercialBank a,b;
 @BeforeEach void setup(){EconomySavedData.resetRuntimeState();BankingManager.ensureDefaultBanks();var list=BankingManager.banks().values().stream().toList();a=list.get(0);b=list.get(1);AccountManager.deposit(player,10_000);AccountManager.deposit(other,10_000);}
 @AfterEach void end(){EconomySavedData.resetRuntimeState();}
 @Test void demandDepositAndWithdrawalReclassifyWithoutCopyingWallet(){long reserve=a.ledger().balanceSheet().reserves(),wallet=AccountManager.getBalance(player);var d=BankingManager.depositPlayer(player,a.id(),2_000,1);assertTrue(d.success());assertEquals(wallet-2_000,AccountManager.getBalance(player));assertEquals(2_000,BankingManager.account(d.id()).balance());assertEquals(reserve+2_000,a.ledger().balanceSheet().reserves());assertEquals(2_000,a.ledger().balanceSheet().demandDeposits());assertTrue(BankingManager.withdrawPlayer(player,d.id(),500,1).success());assertEquals(wallet-1_500,AccountManager.getBalance(player));assertEquals(1_500,BankingManager.account(d.id()).balance());assertTrue(a.ledger().balanceSheet().balanced());}
 @Test void crossBankPaymentMovesReservesButNotTheirSystemTotal(){var x=BankingManager.depositPlayer(player,a.id(),3_000,1);var y=BankingManager.depositPlayer(other,b.id(),1_000,1);long total=a.ledger().balanceSheet().reserves()+b.ledger().balanceSheet().reserves();assertTrue(BankingManager.transfer(player,x.id(),y.id(),700,1).success());assertEquals(2_300,BankingManager.account(x.id()).balance());assertEquals(1_700,BankingManager.account(y.id()).balance());assertEquals(total,a.ledger().balanceSheet().reserves()+b.ledger().balanceSheet().reserves());assertTrue(a.ledger().balanceSheet().balanced());assertTrue(b.ledger().balanceSheet().balanced());}
 @Test void timeDepositLocksRateAndMaturesOnlyOnce(){var demand=BankingManager.depositPlayer(player,a.id(),5_000,0);var r=BankingManager.openTimeDeposit(player,demand.id(),4_000,2,0);assertTrue(r.success());int rate=BankingManager.timeDeposits().get(r.id()).lockedRateBps();finance.policy.MonetaryPolicyService.setBenchmarkRate(1,2_000,"test");BankingManager.processDay(2);TimeDeposit td=BankingManager.timeDeposits().get(r.id());assertEquals(rate,td.lockedRateBps());assertEquals(TimeDepositStatus.MATURED,td.status());long balance=BankingManager.account(td.accountId()).balance();BankingManager.processDay(2);assertEquals(balance,BankingManager.account(td.accountId()).balance());assertTrue(BankingManager.redeemTimeDeposit(player,td.id(),2).success());assertEquals(TimeDepositStatus.REDEEMED,td.status());assertFalse(BankingManager.redeemTimeDeposit(player,td.id(),2).success());}
 @Test void resolutionCombinesInsuranceLimitAndNeverDuplicatesDeposit(){AccountManager.deposit(player,130_000);var demand=BankingManager.depositPlayer(player,a.id(),130_000,0);assertTrue(demand.success());var term=BankingManager.openTimeDeposit(player,demand.id(),50_000,10,0);assertTrue(term.success());a.setStatus(BankStatus.RESOLUTION);assertTrue(DepositInsuranceService.resolve(a.id(),1));assertEquals(BankStatus.FAILED,a.status());long bridgeBalance=BankingManager.accounts().values().stream().filter(x->x.ownerId().equals(player)&&!x.bankId().equals(a.id())).mapToLong(BankCustomerAccount::balance).sum();long residual=BankingManager.accounts().values().stream().filter(x->x.ownerId().equals(player)&&x.bankId().equals(a.id())).mapToLong(BankCustomerAccount::balance).sum();assertEquals(DepositInsuranceService.PER_CUSTOMER_LIMIT,bridgeBalance);assertEquals(30_000,residual);assertFalse(DepositInsuranceService.resolve(a.id(),1));}
 @Test void successfulBankActionsWriteUnifiedHistory(){var first=BankingManager.depositPlayer(player,a.id(),2_000,1);var second=BankingManager.depositPlayer(other,b.id(),1_000,1);assertTrue(BankingManager.transfer(player,first.id(),second.id(),250,1).success());assertTrue(BankingManager.withdrawPlayer(player,first.id(),100,1).success());assertTrue(AccountManager.getTransactions().stream().anyMatch(t->t.getType()==finance.account.TransactionType.BANK_DEPOSIT));assertTrue(AccountManager.getTransactions().stream().anyMatch(t->t.getType()==finance.account.TransactionType.BANK_TRANSFER));assertTrue(AccountManager.getTransactions().stream().anyMatch(t->t.getType()==finance.account.TransactionType.BANK_WITHDRAWAL));}
 @Test void demandInterestIsPostedOncePerDayAndBalancesCustomerWithLedger(){AccountManager.deposit(player,20_000_000);var demand=BankingManager.depositPlayer(player,a.id(),20_000_000,0);long before=BankingManager.account(demand.id()).balance();BankingManager.processDay(1);long after=BankingManager.account(demand.id()).balance();assertTrue(after>before);assertEquals(after,a.ledger().balanceSheet().demandDeposits());BankingManager.processDay(1);assertEquals(after,BankingManager.account(demand.id()).balance());assertTrue(a.ledger().balanceSheet().balanced());}
 @Test void dailyCycleRepairsRequiredReserveDeficitThroughRecordedLiquidity(){long reserve=a.ledger().balanceSheet().reserves();assertTrue(a.ledger().post(0,UUID.randomUUID(),BankLedgerAccount.EQUITY_PAID_IN,BankLedgerAccount.ASSET_RESERVE,reserve-1,BankLedgerReason.DEMAND_WITHDRAWAL));assertTrue(a.ledger().balanceSheet().reserves()<BankRegulatoryService.requiredReserves(a));BankingManager.processDay(0);assertTrue(a.ledger().balanceSheet().reserves()>=BankRegulatoryService.requiredReserves(a));assertFalse(InterbankMarketService.loans().isEmpty());assertTrue(a.ledger().balanceSheet().balanced());}
}
