package finance.bank;

import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class BankLedgerTest {
 @Test void initialCapitalAndDepositRemainBalancedAndReferenceIsIdempotent(){UUID bank=UUID.randomUUID(),r1=UUID.randomUUID(),r2=UUID.randomUUID();BankLedger l=new BankLedger(bank);assertTrue(l.post(0,r1,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.EQUITY_PAID_IN,1_000,BankLedgerReason.INITIAL_CAPITAL));assertFalse(l.post(0,r1,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.EQUITY_PAID_IN,1_000,BankLedgerReason.INITIAL_CAPITAL));assertTrue(l.post(1,r2,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,500,BankLedgerReason.DEMAND_DEPOSIT));assertTrue(l.balanceSheet().balanced());assertEquals(1_500,l.balanceSheet().totalAssets());assertEquals(500,l.balanceSheet().demandDeposits());}
 @Test void underflowOverflowAndMalformedBatchAreAtomic(){BankLedger l=new BankLedger(UUID.randomUUID());UUID init=UUID.randomUUID();assertTrue(l.post(0,init,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.EQUITY_PAID_IN,10,BankLedgerReason.INITIAL_CAPITAL));assertFalse(l.post(1,UUID.randomUUID(),BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_RESERVE,11,BankLedgerReason.DEMAND_WITHDRAWAL));assertEquals(10,l.balance(BankLedgerAccount.ASSET_RESERVE));assertTrue(l.balanceSheet().balanced());}
 @Test void restoredEntriesRebuildSameBalancedSheet(){UUID id=UUID.randomUUID();BankLedger a=new BankLedger(id);a.post(0,UUID.randomUUID(),BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.EQUITY_PAID_IN,100,BankLedgerReason.INITIAL_CAPITAL);a.post(1,UUID.randomUUID(),BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,20,BankLedgerReason.DEMAND_DEPOSIT);BankLedger b=new BankLedger(id);assertTrue(b.restore(a.entries()));assertEquals(a.balanceSheet(),b.balanceSheet());}
 @Test void boundedHistoryCompactionStillRestoresCurrentBalances(){UUID id=UUID.randomUUID();BankLedger a=new BankLedger(id);a.post(0,UUID.randomUUID(),BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.EQUITY_PAID_IN,10_000,BankLedgerReason.INITIAL_CAPITAL);for(int i=0;i<BankLedger.MAX_ENTRIES+5;i++)assertTrue(a.post(i+1,UUID.randomUUID(),BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,1,BankLedgerReason.DEMAND_DEPOSIT));assertTrue(a.entries().size()<=BankLedger.MAX_ENTRIES);BankLedger b=new BankLedger(id);assertTrue(b.restore(a.entries()));assertEquals(a.balanceSheet(),b.balanceSheet());}
}
