package finance.bank;
import finance.data.EconomySavedData;import org.junit.jupiter.api.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class InterbankAndRiskTest {CommercialBank a,b;@BeforeEach void setup(){EconomySavedData.resetRuntimeState();BankingManager.ensureDefaultBanks();var x=BankingManager.banks().values().stream().toList();a=x.get(0);b=x.get(1);}@AfterEach void end(){EconomySavedData.resetRuntimeState();}
 @Test void interbankLoanCreatesMirroredClaimsAndConservesReserves(){long total=a.ledger().balanceSheet().reserves()+b.ledger().balanceSheet().reserves();UUID id=InterbankMarketService.issue(a.id(),b.id(),100_000,0);assertNotNull(id);assertEquals(100_000,a.ledger().balanceSheet().interbankAssets());assertEquals(100_000,b.ledger().balanceSheet().interbankLiabilities());assertEquals(total,a.ledger().balanceSheet().reserves()+b.ledger().balanceSheet().reserves());InterbankMarketService.processDay(1);assertEquals(InterbankLoanStatus.REPAID,InterbankMarketService.loans().get(id).status());assertEquals(0,a.ledger().balanceSheet().interbankAssets());assertEquals(0,b.ledger().balanceSheet().interbankLiabilities());}
 @Test void centralFacilityIsExplicitBoundedLiability(){long before=b.ledger().balanceSheet().reserves();assertEquals(50_000,CentralBankLiquidityService.borrow(b.id(),50_000,0));assertEquals(before+50_000,b.ledger().balanceSheet().reserves());assertEquals(50_000,b.ledger().balanceSheet().centralBankBorrowing());assertEquals(50_000,CentralBankLiquidityService.cumulativeIssued());}
 @Test void stressTestIsPureAndBounded(){BankStatus before=a.status();var result=BankStressTestService.run(new BankStressTestService.Scenario(10_000,5_000,10_000,2_000));assertEquals(BankingManager.banks().size(),result.banks().size());assertEquals(before,a.status());assertTrue(result.contagionRounds()<=BankStressTestService.MAX_CONTAGION_ROUNDS);}
 @Test void rateShockActuallyReducesBondValueAndUsesConfiguredBound(){assertTrue(a.ledger().post(0,UUID.randomUUID(),BankLedgerAccount.ASSET_BOND,BankLedgerAccount.EQUITY_RETAINED,100_000,BankLedgerReason.INITIAL_CAPITAL));var calm=BankStressTestService.run(new BankStressTestService.Scenario(0,0,0,0));var shocked=BankStressTestService.run(new BankStressTestService.Scenario(0,0,0,2_000));long calmLoss=calm.banks().stream().filter(x->x.bankId().equals(a.id())).findFirst().orElseThrow().loss();long shockLoss=shocked.banks().stream().filter(x->x.bankId().equals(a.id())).findFirst().orElseThrow().loss();assertEquals(0,calmLoss);assertEquals(20_000,shockLoss);assertTrue(shocked.contagionRounds()<=finance.config.FinanceConfig.bankStressMaxRounds());}
 @Test void reserveInterestIsExplicitAndSameDayIdempotent(){long before=a.ledger().balanceSheet().reserves();CentralBankLiquidityService.payReserveInterest(0);long paid=CentralBankLiquidityService.cumulativeReserveInterest();assertTrue(paid>0);long after=a.ledger().balanceSheet().reserves();CentralBankLiquidityService.payReserveInterest(0);assertEquals(paid,CentralBankLiquidityService.cumulativeReserveInterest());assertEquals(after,a.ledger().balanceSheet().reserves());assertTrue(after>before);assertTrue(a.ledger().balanceSheet().balanced());}
}
