package finance.bank;

public enum BankLedgerReason {
    INITIAL_CAPITAL, DEMAND_DEPOSIT, DEMAND_WITHDRAWAL, TIME_DEPOSIT_OPEN, TIME_DEPOSIT_INTEREST,
    TIME_DEPOSIT_REDEEM, CROSS_BANK_PAYMENT, COMPANY_LOAN_ISSUE, COMPANY_LOAN_PRINCIPAL,
    COMPANY_LOAN_INTEREST, LOAN_LOSS_PROVISION, INTERBANK_ISSUE, INTERBANK_REPAYMENT,
    INTERBANK_INTEREST, INTERBANK_DEFAULT, CENTRAL_BANK_BORROWING, CENTRAL_BANK_REPAYMENT,
    RESERVE_INTEREST, DEMAND_DEPOSIT_INTEREST, INSURANCE_PREMIUM, RESOLUTION_TRANSFER,
    LOAN_LOSS_RECOVERY, LEDGER_COMPACTION
}
