package finance.bank;

import finance.account.AccountManager;
import finance.account.TransactionRecord;
import finance.account.TransactionType;
import finance.company.Company;
import finance.company.CompanyManager;
import finance.config.FinanceConfig;
import finance.data.EconomySavedData;
import finance.policy.MonetaryPolicyService;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.*;

public final class BankingManager {
    public static final int MAX_BANKS=16,MAX_ACCOUNTS=20_000,MAX_TIME_DEPOSITS=10_000;
    private static final Map<UUID,CommercialBank>BANKS=new LinkedHashMap<>();
    private static final Map<UUID,BankCustomerAccount>ACCOUNTS=new LinkedHashMap<>();
    private static final Map<UUID,TimeDeposit>TIME_DEPOSITS=new LinkedHashMap<>();
    private static long lastDepositDay=-1,lastSnapshotDay=-1;
    private BankingManager(){ }

    public static synchronized void ensureDefaultBanks(){if(!BANKS.isEmpty())return;String[][]defs={{"MCB","Minecraft Commercial Bank"},{"RVB","River Valley Bank"},{"CRB","Creeper Reserve Bank"},{"ENB","Ender National Bank"}};for(int i=0;i<FinanceConfig.defaultBankCount();i++)createDefault(defs[i][0],defs[i][1],i+1);EconomySavedData.markDirty();}
    private static void createDefault(String code,String name,int suffix){UUID id=UUID.nameUUIDFromBytes(("finance-bank-"+suffix).getBytes(StandardCharsets.UTF_8));BankPolicy policy=new BankPolicy(FinanceConfig.bankDemandSpreadBps(),FinanceConfig.bankTimeSpreadBps(),FinanceConfig.bankLoanSpreadBps(),FinanceConfig.bankDemandReserveBps(),FinanceConfig.bankSingleBorrowerLimitBps());CommercialBank bank=new CommercialBank(id,code,name,BankStatus.ACTIVE,FinanceConfig.bankInitialCapital(),policy);UUID ref=UUID.nameUUIDFromBytes(("finance-bank-capital-"+suffix).getBytes(StandardCharsets.UTF_8));if(bank.ledger().post(0,ref,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.EQUITY_PAID_IN,bank.paidInCapital(),BankLedgerReason.INITIAL_CAPITAL))BANKS.put(id,bank);}
    public static synchronized Result depositPlayer(UUID player,UUID bankId,long amount,long day){ensureDefaultBanks();CommercialBank bank=BANKS.get(bankId);if(!FinanceConfig.bankingEnabled()||player==null||bank==null||!bank.acceptsNewBusiness()||amount<=0||day<0)return Result.fail("存款参数无效");BankCustomerAccount account=demandAccount(bankId,player,CustomerType.PLAYER,day,true);UUID ref=UUID.randomUUID();if(account==null||!account.canCredit(amount)||!bank.ledger().canPost(ref,List.of(new BankLedger.Draft(BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,amount,BankLedgerReason.DEMAND_DEPOSIT)))||!AccountManager.withdraw(player,amount))return Result.fail("钱包余额不足或银行拒绝存款");if(!bank.ledger().post(day,ref,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,amount,BankLedgerReason.DEMAND_DEPOSIT)){AccountManager.deposit(player,amount);return Result.fail("银行入账失败");}if(!account.credit(amount))throw new IllegalStateException("validated deposit failed");record(player,bankId,amount,TransactionType.BANK_DEPOSIT,player,bank.name());EconomySavedData.markDirty();return Result.ok(account.id(),"活期存款成功");}
    public static synchronized Result withdrawPlayer(UUID player,UUID accountId,long amount,long day){BankCustomerAccount account=ACCOUNTS.get(accountId);CommercialBank bank=account==null?null:BANKS.get(account.bankId());if(player==null||account==null||bank==null||account.ownerType()!=CustomerType.PLAYER||!account.ownerId().equals(player)||account.type()!=BankAccountType.DEMAND_DEPOSIT||account.status()!=BankAccountStatus.ACTIVE||amount<=0||account.available()<amount||!AccountManager.canDeposit(player,amount))return Result.fail("提款参数无效");if(bank.ledger().balance(BankLedgerAccount.ASSET_RESERVE)<amount&&!BankLiquidityService.ensureReserves(bank.id(),amount,day))return Result.fail("银行流动性不足");UUID ref=UUID.randomUUID();if(!bank.ledger().canPost(ref,List.of(new BankLedger.Draft(BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_RESERVE,amount,BankLedgerReason.DEMAND_WITHDRAWAL))))return Result.fail("银行账务无法结算");if(!account.debit(amount))return Result.fail("存款余额不足");if(!bank.ledger().post(day,ref,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_RESERVE,amount,BankLedgerReason.DEMAND_WITHDRAWAL)){account.credit(amount);return Result.fail("银行账务失败");}if(!AccountManager.deposit(player,amount))throw new IllegalStateException("validated wallet credit failed");record(bank.id(),player,amount,TransactionType.BANK_WITHDRAWAL,player,bank.name());EconomySavedData.markDirty();return Result.ok(account.id(),"提款成功");}
    public static synchronized Result transfer(UUID owner,UUID fromId,UUID toId,long amount,long day){BankCustomerAccount from=ACCOUNTS.get(fromId),to=ACCOUNTS.get(toId);if(owner==null||from==null||to==null||!from.ownerId().equals(owner)||from.type()!=BankAccountType.DEMAND_DEPOSIT||to.type()!=BankAccountType.DEMAND_DEPOSIT||from.status()!=BankAccountStatus.ACTIVE||to.status()!=BankAccountStatus.ACTIVE||amount<=0||from.available()<amount||!to.canCredit(amount)||from.id().equals(to.id()))return Result.fail("转账参数无效");CommercialBank fb=BANKS.get(from.bankId()),tb=BANKS.get(to.bankId());if(fb==null||tb==null)return Result.fail("银行不存在");if(fb.id().equals(tb.id())){from.debit(amount);to.credit(amount);record(from.ownerId(),to.ownerId(),amount,TransactionType.BANK_TRANSFER,owner,fb.name());EconomySavedData.markDirty();return Result.ok(to.id(),"同行转账成功");}if(fb.ledger().balance(BankLedgerAccount.ASSET_RESERVE)<amount&&!BankLiquidityService.ensureReserves(fb.id(),amount,day))return Result.fail("付款行准备金不足");UUID ref=UUID.randomUUID();List<BankLedger.Draft> fd=List.of(new BankLedger.Draft(BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_RESERVE,amount,BankLedgerReason.CROSS_BANK_PAYMENT));List<BankLedger.Draft> td=List.of(new BankLedger.Draft(BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,amount,BankLedgerReason.CROSS_BANK_PAYMENT));if(!fb.ledger().canPost(ref,fd)||!tb.ledger().canPost(ref,td))return Result.fail("跨行结算预检失败");from.debit(amount);to.credit(amount);if(!fb.ledger().postBatch(day,ref,fd)||!tb.ledger().postBatch(day,ref,td))throw new IllegalStateException("validated cross-bank batch failed");record(from.ownerId(),to.ownerId(),amount,TransactionType.BANK_TRANSFER,owner,fb.name()+" -> "+tb.name());EconomySavedData.markDirty();return Result.ok(to.id(),"跨行转账成功");}
    public static synchronized Result openTimeDeposit(UUID owner,UUID demandId,long amount,int termDays,long day){BankCustomerAccount demand=ACCOUNTS.get(demandId);CommercialBank bank=demand==null?null:BANKS.get(demand.bankId());if(!FinanceConfig.bankingEnabled()||owner==null||demand==null||bank==null||!demand.ownerId().equals(owner)||demand.ownerType()!=CustomerType.PLAYER||demand.type()!=BankAccountType.DEMAND_DEPOSIT||amount<=0||demand.available()<amount||termDays<2||termDays>365||TIME_DEPOSITS.size()>=MAX_TIME_DEPOSITS)return Result.fail("定期存款参数无效");long maturity;try{maturity=Math.addExact(day,termDays);}catch(ArithmeticException e){return Result.fail("到期日溢出");}int rate=Math.max(0,Math.min(20_000,MonetaryPolicyService.benchmarkRateBasisPoints()-bank.policy().timeSpreadBps()+Math.min(500,termDays*3)));UUID id=UUID.randomUUID(),accountId=UUID.randomUUID(),ref=UUID.randomUUID();if(!bank.ledger().canPost(ref,List.of(new BankLedger.Draft(BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.LIABILITY_TIME_DEPOSIT,amount,BankLedgerReason.TIME_DEPOSIT_OPEN))))return Result.fail("银行账务拒绝");demand.debit(amount);BankCustomerAccount time=new BankCustomerAccount(accountId,bank.id(),owner,CustomerType.PLAYER,BankAccountType.TIME_DEPOSIT,amount,0,day,BankAccountStatus.ACTIVE);ACCOUNTS.put(accountId,time);TIME_DEPOSITS.put(id,new TimeDeposit(id,bank.id(),owner,accountId,amount,rate,day,maturity,0,day,TimeDepositStatus.ACTIVE));if(!bank.ledger().post(day,ref,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.LIABILITY_TIME_DEPOSIT,amount,BankLedgerReason.TIME_DEPOSIT_OPEN))throw new IllegalStateException();record(owner,bank.id(),amount,TransactionType.TIME_DEPOSIT_OPEN,owner,bank.name()+"/"+termDays+"d");EconomySavedData.markDirty();return Result.ok(id,"定期存款已创建");}
    public static synchronized Result redeemTimeDeposit(UUID owner,UUID depositId,long day){TimeDeposit td=TIME_DEPOSITS.get(depositId);if(td==null||owner==null||!td.ownerId().equals(owner)||td.status()!=TimeDepositStatus.MATURED)return Result.fail("定期存款尚未到期或已兑付");BankCustomerAccount time=ACCOUNTS.get(td.accountId()),demand=demandAccount(td.bankId(),owner,CustomerType.PLAYER,day,true);CommercialBank bank=BANKS.get(td.bankId());long amount=time==null?0:time.balance();UUID ref=UUID.randomUUID();if(amount<=0||demand==null||!demand.canCredit(amount)||!bank.ledger().canPost(ref,List.of(new BankLedger.Draft(BankLedgerAccount.LIABILITY_TIME_DEPOSIT,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,amount,BankLedgerReason.TIME_DEPOSIT_REDEEM))))return Result.fail("兑付预检失败");time.debit(amount);time.close();demand.credit(amount);td.setStatus(TimeDepositStatus.REDEEMED);bank.ledger().post(day,ref,BankLedgerAccount.LIABILITY_TIME_DEPOSIT,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,amount,BankLedgerReason.TIME_DEPOSIT_REDEEM);record(bank.id(),owner,amount,TransactionType.TIME_DEPOSIT_REDEEM,owner,bank.name());EconomySavedData.markDirty();return Result.ok(depositId,"定期存款已转入活期");}
    public static synchronized void processDay(long day){ensureDefaultBanks();if(day<=lastDepositDay)return;for(long d=lastDepositDay+1;d<=day;d++){accrueDemandDeposits(d);accrueTimeDeposits(d);InterbankMarketService.processDay(d);CentralBankLiquidityService.processDay(d);DepositInsuranceService.processDay(d);for(CommercialBank b:new ArrayList<>(BANKS.values())){if(b.acceptsNewBusiness()){long required=BankRegulatoryService.requiredReserves(b);if(b.ledger().balance(BankLedgerAccount.ASSET_RESERVE)<required)BankLiquidityService.ensureReserves(b.id(),required,d);}BankRegulatoryService.evaluate(b);}lastDepositDay=d;if(d==Long.MAX_VALUE)break;}EconomySavedData.markDirty();}
    private static void accrueDemandDeposits(long day){for(BankCustomerAccount account:ACCOUNTS.values()){if(account.type()!=BankAccountType.DEMAND_DEPOSIT||account.status()!=BankAccountStatus.ACTIVE||account.balance()<=0)continue;CommercialBank bank=BANKS.get(account.bankId());if(bank==null||bank.status()==BankStatus.FAILED||bank.status()==BankStatus.MERGED)continue;int rate=Math.max(0,MonetaryPolicyService.benchmarkRateBasisPoints()-bank.policy().demandSpreadBps());long interest=BigInteger.valueOf(account.balance()).multiply(BigInteger.valueOf(rate)).divide(BigInteger.valueOf((long)FinanceConfig.annualMcDays()*10_000)).min(BigInteger.valueOf(Long.MAX_VALUE)).longValue();if(interest<=0||!account.canCredit(interest))continue;UUID ref=UUID.nameUUIDFromBytes((account.id()+":demand-interest:"+day).getBytes(StandardCharsets.UTF_8));if(bank.ledger().post(day,ref,BankLedgerAccount.EXPENSE_INTEREST,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,interest,BankLedgerReason.DEMAND_DEPOSIT_INTEREST))account.credit(interest);}}
    private static void accrueTimeDeposits(long day){for(TimeDeposit td:TIME_DEPOSITS.values()){if(td.status()!=TimeDepositStatus.ACTIVE||day<=td.lastAccrualDay())continue;BankCustomerAccount account=ACCOUNTS.get(td.accountId());CommercialBank bank=BANKS.get(td.bankId());long through=Math.min(day,td.maturityDay()),days=through-td.lastAccrualDay();if(days>0){BigInteger exact=BigInteger.valueOf(td.principal()).multiply(BigInteger.valueOf(td.lockedRateBps())).multiply(BigInteger.valueOf(days)).divide(BigInteger.valueOf((long)FinanceConfig.annualMcDays()*10_000));long interest=exact.min(BigInteger.valueOf(Long.MAX_VALUE)).longValue();if(interest>0&&account!=null&&account.canCredit(interest)){UUID ref=UUID.nameUUIDFromBytes((td.id()+":interest:"+through).getBytes(StandardCharsets.UTF_8));if(bank.ledger().post(through,ref,BankLedgerAccount.EXPENSE_INTEREST,BankLedgerAccount.LIABILITY_TIME_DEPOSIT,interest,BankLedgerReason.TIME_DEPOSIT_INTEREST)){account.credit(interest);td.addInterest(interest,through);}}else td.addInterest(0,through);}if(day>=td.maturityDay())td.setStatus(TimeDepositStatus.MATURED);}}
    public static synchronized BankCustomerAccount demandAccount(UUID bankId,UUID owner,CustomerType type,long day,boolean create){BankCustomerAccount found=ACCOUNTS.values().stream().filter(a->a.bankId().equals(bankId)&&a.ownerId().equals(owner)&&a.ownerType()==type&&a.type()==BankAccountType.DEMAND_DEPOSIT&&a.status()!=BankAccountStatus.CLOSED).findFirst().orElse(null);if(found==null&&create&&BANKS.containsKey(bankId)&&ACCOUNTS.size()<MAX_ACCOUNTS){found=new BankCustomerAccount(UUID.randomUUID(),bankId,owner,type,BankAccountType.DEMAND_DEPOSIT,0,0,Math.max(0,day),BankAccountStatus.ACTIVE);ACCOUNTS.put(found.id(),found);}return found;}
    public static synchronized boolean originateCompanyDepositLoan(UUID bankId,UUID companyId,long principal,long day,UUID reference){CommercialBank bank=BANKS.get(bankId);Company company=CompanyManager.getCompany(companyId);if(bank==null||company==null||!bank.acceptsNewBusiness()||principal<=0)return false;BankCustomerAccount account=demandAccount(bankId,companyId,CustomerType.COMPANY,day,true);List<BankLedger.Draft> drafts=List.of(new BankLedger.Draft(BankLedgerAccount.ASSET_COMPANY_LOAN,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,principal,BankLedgerReason.COMPANY_LOAN_ISSUE));if(account==null||!account.canCredit(principal)||!bank.ledger().canPost(reference,drafts))return false;account.credit(principal);bank.ledger().postBatch(day,reference,drafts);EconomySavedData.markDirty();return true;}
    public static synchronized boolean repayCompanyLoan(UUID bankId,UUID companyId,long principal,long interest,long day,UUID reference){CommercialBank bank=BANKS.get(bankId);BankCustomerAccount account=demandAccount(bankId,companyId,CustomerType.COMPANY,day,false);long total;try{total=Math.addExact(principal,interest);}catch(ArithmeticException e){return false;}List<BankLedger.Draft> drafts=new ArrayList<>();if(principal>0)drafts.add(new BankLedger.Draft(BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_COMPANY_LOAN,principal,BankLedgerReason.COMPANY_LOAN_PRINCIPAL));if(interest>0)drafts.add(new BankLedger.Draft(BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.INCOME_INTEREST,interest,BankLedgerReason.COMPANY_LOAN_INTEREST));if(account==null||account.available()<total||!bank.ledger().canPost(reference,drafts))return false;account.debit(total);bank.ledger().postBatch(day,reference,drafts);EconomySavedData.markDirty();return true;}
    public static synchronized boolean canApplyLoanRecovery(UUID bankId,long amount){CommercialBank b=BANKS.get(bankId);return b!=null&&amount>0&&b.ledger().balance(BankLedgerAccount.ASSET_COMPANY_LOAN)>=amount;}
    public static synchronized boolean applyLoanRecovery(UUID bankId,long amount,long day,UUID reference){CommercialBank b=BANKS.get(bankId);if(b==null||amount<=0)return false;long release=Math.min(amount,b.ledger().balance(BankLedgerAccount.CONTRA_LOAN_LOSS_RESERVE));List<BankLedger.Draft>drafts=new ArrayList<>();drafts.add(new BankLedger.Draft(BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.ASSET_COMPANY_LOAN,amount,BankLedgerReason.COMPANY_LOAN_PRINCIPAL));if(release>0)drafts.add(new BankLedger.Draft(BankLedgerAccount.CONTRA_LOAN_LOSS_RESERVE,BankLedgerAccount.INCOME_FEE,release,BankLedgerReason.LOAN_LOSS_RECOVERY));boolean posted=b.ledger().postBatch(day,reference,drafts);if(posted)BankRegulatoryService.evaluate(b);return posted;}
    public static synchronized boolean payInsurancePremium(UUID bankId,UUID poolAccountId,long amount,long day,UUID reference){
        CommercialBank b=BANKS.get(bankId);
        if(b==null||poolAccountId==null||amount<=0||b.ledger().balance(BankLedgerAccount.ASSET_RESERVE)<amount||!AccountManager.canDeposit(poolAccountId,amount))return false;
        List<BankLedger.Draft> drafts=List.of(new BankLedger.Draft(BankLedgerAccount.EXPENSE_INSURANCE,BankLedgerAccount.ASSET_RESERVE,amount,BankLedgerReason.INSURANCE_PREMIUM));
        if(!b.ledger().canPost(reference,drafts)||!b.ledger().postBatch(day,reference,drafts))return false;
        if(!AccountManager.deposit(poolAccountId,amount))throw new IllegalStateException("validated insurance pool credit failed");
        BankRegulatoryService.evaluate(b);EconomySavedData.markDirty();return true;
    }
    public static synchronized boolean withdrawCompanyToCash(UUID owner,UUID bankId,long amount,long day){Company c=CompanyManager.getCompanyByOwner(owner);BankCustomerAccount a=c==null?null:demandAccount(bankId,c.getCompanyId(),CustomerType.COMPANY,day,false);CommercialBank b=BANKS.get(bankId);if(c==null||a==null||b==null||amount<=0||a.available()<amount||!c.canDeposit(amount)||b.ledger().balance(BankLedgerAccount.ASSET_RESERVE)<amount)return false;UUID ref=UUID.randomUUID();if(!b.ledger().canPost(ref,List.of(new BankLedger.Draft(BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_RESERVE,amount,BankLedgerReason.DEMAND_WITHDRAWAL))))return false;a.debit(amount);b.ledger().post(day,ref,BankLedgerAccount.LIABILITY_DEMAND_DEPOSIT,BankLedgerAccount.ASSET_RESERVE,amount,BankLedgerReason.DEMAND_WITHDRAWAL);if(!c.deposit(amount))throw new IllegalStateException();return true;}
    public static synchronized void closeDay(long day){if(day<0||day<=lastSnapshotDay)return;for(CommercialBank bank:BANKS.values()){BankBalanceSheet s=bank.ledger().balanceSheet();if(!s.balanced())continue;long previousEquity=bank.snapshots().isEmpty()?bank.paidInCapital():bank.snapshots().get(bank.snapshots().size()-1).sheet().equity();long profit;try{profit=Math.subtractExact(s.equity(),previousEquity);}catch(ArithmeticException e){profit=s.equity()>=previousEquity?Long.MAX_VALUE:Long.MIN_VALUE;}long npl=finance.debt.CompanyLoanManager.loans().values().stream().filter(l->l.lenderType()==finance.debt.LoanLenderType.COMMERCIAL_BANK&&l.lenderId().equals(bank.id())&&l.status()==finance.debt.LoanStatus.DEFAULTED).mapToLong(finance.debt.CompanyLoan::outstandingPrincipal).reduce(0,BankingManager::safeAdd);bank.addSnapshot(new BankBalanceSheetSnapshot(bank.id(),day,s,profit,npl,BankRegulatoryService.liquidityCoverageBps(bank),BankRegulatoryService.capitalAdequacyBps(bank)));}lastSnapshotDay=day;EconomySavedData.markDirty();}
    public static Map<UUID,CommercialBank> banks(){return Collections.unmodifiableMap(BANKS);}public static Map<UUID,BankCustomerAccount> accounts(){return Collections.unmodifiableMap(ACCOUNTS);}public static Map<UUID,TimeDeposit> timeDeposits(){return Collections.unmodifiableMap(TIME_DEPOSITS);}public static CommercialBank bank(UUID id){return BANKS.get(id);}public static BankCustomerAccount account(UUID id){return ACCOUNTS.get(id);}public static long lastDepositDay(){return lastDepositDay;}public static long lastSnapshotDay(){return lastSnapshotDay;}
    public static synchronized void putBankDirect(CommercialBank b){if(b!=null&&BANKS.size()<MAX_BANKS)BANKS.put(b.id(),b);}public static synchronized void putAccountDirect(BankCustomerAccount a){if(a!=null&&ACCOUNTS.size()<MAX_ACCOUNTS)ACCOUNTS.put(a.id(),a);}public static synchronized void putTimeDepositDirect(TimeDeposit d){if(d!=null&&TIME_DEPOSITS.size()<MAX_TIME_DEPOSITS)TIME_DEPOSITS.put(d.id(),d);}public static void restoreDays(long deposit,long snapshot){lastDepositDay=Math.max(-1,deposit);lastSnapshotDay=Math.max(-1,snapshot);}public static synchronized void clearDirect(){BANKS.clear();ACCOUNTS.clear();TIME_DEPOSITS.clear();lastDepositDay=-1;lastSnapshotDay=-1;}
    public static synchronized void removeBankDirect(UUID id){BANKS.remove(id);ACCOUNTS.entrySet().removeIf(e->e.getValue().bankId().equals(id));TIME_DEPOSITS.entrySet().removeIf(e->e.getValue().bankId().equals(id));}
    private static void record(UUID from,UUID to,long amount,TransactionType type,UUID player,String object){AccountManager.addTransactionRecord(new TransactionRecord(from,to,amount,type,player,object,1));}
    private static long safeAdd(long a,long b){return a>Long.MAX_VALUE-b?Long.MAX_VALUE:a+b;}
    public record Result(boolean success,UUID id,String message){public static Result ok(UUID id,String m){return new Result(true,id,m);}public static Result fail(String m){return new Result(false,null,m);}}
}
