package finance.bank;

import finance.config.FinanceConfig;import finance.data.EconomySavedData;import finance.policy.MonetaryPolicyService;
import java.math.BigInteger;import java.util.*;
public final class CentralBankLiquidityService {public static final long FACILITY_LIMIT=50_000_000;public static final int MAX_LOANS=1_000;private static final Map<UUID,CentralBankLiquidityLoan>LOANS=new LinkedHashMap<>();private static long cumulativeIssued,cumulativeReserveInterest,lastProcessedDay=-1,lastReserveInterestDay=-1;private CentralBankLiquidityService(){}
    public static synchronized long borrow(UUID bankId,long amount,long day){CommercialBank b=BankingManager.bank(bankId);if(b==null||amount<=0||day<0||LOANS.size()>=MAX_LOANS||b.ledger().balanceSheet().equity()<=0||cumulativeIssued>FACILITY_LIMIT-amount)return 0;int rate=Math.min(20_000,MonetaryPolicyService.benchmarkRateBasisPoints()+FinanceConfig.bankCentralPenaltyBps());UUID id=UUID.randomUUID();if(!b.ledger().post(day,id,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.LIABILITY_CENTRAL_BANK,amount,BankLedgerReason.CENTRAL_BANK_BORROWING))return 0;LOANS.put(id,new CentralBankLiquidityLoan(id,bankId,amount,rate,day,day+3,CentralBankLoanStatus.ACTIVE));cumulativeIssued+=amount;EconomySavedData.markDirty();return amount;}
    public static synchronized void processDay(long day){payReserveInterest(day);if(day<=lastProcessedDay)return;for(var l:LOANS.values())if(l.status()==CentralBankLoanStatus.ACTIVE&&day>=l.maturityDay())repay(l,day);lastProcessedDay=day;EconomySavedData.markDirty();}
    public static synchronized void payReserveInterest(long day){if(day<0||day<=lastReserveInterestDay)return;int rate=Math.max(0,MonetaryPolicyService.benchmarkRateBasisPoints()-200);for(CommercialBank b:BankingManager.banks().values()){long excess=Math.max(0,b.ledger().balance(BankLedgerAccount.ASSET_RESERVE)-BankRegulatoryService.requiredReserves(b));long interest=BigInteger.valueOf(excess).multiply(BigInteger.valueOf(rate)).divide(BigInteger.valueOf((long)FinanceConfig.annualMcDays()*10_000)).min(BigInteger.valueOf(Long.MAX_VALUE)).longValue();if(interest>0){UUID ref=UUID.nameUUIDFromBytes((b.id()+":reserve-interest:"+day).getBytes(java.nio.charset.StandardCharsets.UTF_8));if(b.ledger().post(day,ref,BankLedgerAccount.ASSET_RESERVE,BankLedgerAccount.INCOME_INTEREST,interest,BankLedgerReason.RESERVE_INTEREST))cumulativeReserveInterest=cumulativeReserveInterest>Long.MAX_VALUE-interest?Long.MAX_VALUE:cumulativeReserveInterest+interest;}}lastReserveInterestDay=day;EconomySavedData.markDirty();}
    private static void repay(CentralBankLiquidityLoan l,long day){CommercialBank b=BankingManager.bank(l.bankId());if(b==null){l.setStatus(CentralBankLoanStatus.DEFAULTED);return;}long interest=BigInteger.valueOf(l.principal()).multiply(BigInteger.valueOf(l.rateBasisPoints())).multiply(BigInteger.valueOf(l.maturityDay()-l.issueDay())).divide(BigInteger.valueOf((long)FinanceConfig.annualMcDays()*10_000)).min(BigInteger.valueOf(Long.MAX_VALUE)).longValue();long total;try{total=Math.addExact(l.principal(),interest);}catch(ArithmeticException e){l.setStatus(CentralBankLoanStatus.DEFAULTED);b.setStatus(BankStatus.RESOLUTION);return;}List<BankLedger.Draft>d=new ArrayList<>();d.add(new BankLedger.Draft(BankLedgerAccount.LIABILITY_CENTRAL_BANK,BankLedgerAccount.ASSET_RESERVE,l.principal(),BankLedgerReason.CENTRAL_BANK_REPAYMENT));if(interest>0)d.add(new BankLedger.Draft(BankLedgerAccount.EXPENSE_INTEREST,BankLedgerAccount.ASSET_RESERVE,interest,BankLedgerReason.CENTRAL_BANK_REPAYMENT));UUID ref=UUID.nameUUIDFromBytes((l.id()+":repayment").getBytes(java.nio.charset.StandardCharsets.UTF_8));if(b.ledger().balance(BankLedgerAccount.ASSET_RESERVE)<total||!b.ledger().postBatch(day,ref,d)){l.setStatus(CentralBankLoanStatus.DEFAULTED);b.setStatus(BankStatus.RESOLUTION);}else l.setStatus(CentralBankLoanStatus.REPAID);}
    public static Map<UUID,CentralBankLiquidityLoan>loans(){return Collections.unmodifiableMap(LOANS);}public static long cumulativeIssued(){return cumulativeIssued;}public static long cumulativeReserveInterest(){return cumulativeReserveInterest;}public static long lastProcessedDay(){return lastProcessedDay;}public static long lastReserveInterestDay(){return lastReserveInterestDay;}public static void putDirect(CentralBankLiquidityLoan l){if(l!=null&&LOANS.size()<MAX_LOANS)LOANS.put(l.id(),l);}public static void restore(long issued,long day,long reserveInterest,long interestDay){cumulativeIssued=Math.max(0,issued);lastProcessedDay=Math.max(-1,day);cumulativeReserveInterest=Math.max(0,reserveInterest);lastReserveInterestDay=Math.max(-1,interestDay);}public static void clearDirect(){LOANS.clear();cumulativeIssued=0;cumulativeReserveInterest=0;lastProcessedDay=-1;lastReserveInterestDay=-1;}}
