package finance.account;

/**
 * 交易类型。
 */
public enum TransactionType {
    TRANSFER,
    MARKET_TRADE,
    NPC_BUY,
    NPC_SELL,
    COMMODITY_BUY,
    COMMODITY_SELL,
    STOCK_BUY,
    STOCK_SELL,
    ORDER_CANCEL,
    STOCK_ORDER_CANCEL,
    COMPANY_ACTION,
    COMPANY_CREATE,
    COMPANY_IPO,
    DIVIDEND,
    CONDITIONAL_STOCK_TRIGGER,
    CONDITIONAL_STOCK_CANCEL,
    COMPANY_FINANCING_START,
    COMPANY_FINANCING_SUBSCRIBE,
    COMPANY_FINANCING_SUCCESS,
    COMPANY_FINANCING_REFUND,
    COMPANY_PROPOSAL_CREATE,
    COMPANY_PROPOSAL_VOTE,
    COMPANY_PROPOSAL_RESULT,
    COMPANY_BANKRUPTCY,
    COMPANY_LIQUIDATION,
    ADMIN_GIVE,
    ADMIN_COMMODITY
}
