package finance.company;

public enum CompanyProposalType {
    DIVIDEND,
    SHARE_ISSUE,
    RENAME,
    FUND_USAGE,
    SHARE_BUYBACK,
    TREASURY_RETIREMENT,
    TENDER_OFFER_RESPONSE,
    CONTROL_TRANSFER,
    EMERGENCY_RECAPITALIZATION,
    MAJOR_ASSET_PURCHASE
}
